services:
  devops-types:
    build:
      context: .
      dockerfile: Dockerfile
    image: pervent/devops-types:v0.0.1
    container_name: devops-types
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
    healthcheck:
      test: [ "CMD", "nc", "-z", "127.0.0.1", "8080" ]
      interval: 10s
      timeout: 3s
      retries: 3
